# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapAttrMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='the LDAP attribute name', max_length=255, verbose_name='name')),
                ('sel_expr', models.CharField(help_text='the SELECT $arg part of the SQL statement', max_length=255, verbose_name='SELECT expr')),
                ('from_tbls', models.CharField(help_text='the FROM $arg part of the SQL statement', max_length=255, verbose_name='FROM expr')),
                ('join_where', models.CharField(blank=True, default=None, help_text='the WHERE ... xx.xx=yy.yy ... part of the SQL statement if applicable. A null is allowed if you are not doing a join.', max_length=255, null=True, verbose_name='WHERE expr')),
                ('add_proc', models.CharField(blank=True, default=None, help_text='the SQL code when an LDAP create is called', max_length=255, null=True, verbose_name='on CREATE expr')),
                ('delete_proc', models.CharField(blank=True, default=None, help_text='the SQL code when an LDAP delete is called', max_length=255, null=True, verbose_name='on DELETE expr')),
                ('param_order', models.IntegerField(default=3, verbose_name='param order')),
                ('expect_return', models.IntegerField(default=0, help_text='what to expect when the query is successful (ie not an error)', verbose_name='expect return code')),
            ],
            options={
                'verbose_name_plural': 'ldap attributes mappings',
                'verbose_name': 'ldap attribute mapping',
                'db_table': 'ldap_attr_mappings',
            },
        ),
        migrations.CreateModel(
            name='LdapEntriesObjectClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('oc_name', models.CharField(help_text="the name of the objectClass; it MUST match the name of an objectClass that is loaded in slapd's schema", max_length=254, verbose_name='ObjectClass name')),
            ],
            options={
                'verbose_name_plural': 'Ldap entry objectclasses',
                'verbose_name': 'Ldap entry objectclass',
                'db_table': 'ldap_entry_objclasses',
            },
        ),
        migrations.CreateModel(
            name='LdapEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dn', models.CharField(max_length=254, unique=True, verbose_name='Distingieshed names')),
                ('parent', models.IntegerField(help_text='what level in the LDAP tree this is located at, starting with 0 (zero)')),
                ('keyval', models.IntegerField(help_text='refers back to the id of the relevant row of the table the data is contained in. These rows are identified by a number that is a primary key')),
            ],
            options={
                'verbose_name_plural': 'Ldap entries',
                'verbose_name': 'Ldap entry',
                'db_table': 'ldap_entries',
            },
        ),
        migrations.CreateModel(
            name='LdapOcMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, help_text="the name of the objectClass; it MUST match the name of an objectClass that is loaded in slapd's schema", max_length=64, verbose_name='name')),
                ('keytbl', models.CharField(help_text='the table where entities for the objectClass are held. The name of the table that is referenced for the primary key of an entry', max_length=255, verbose_name='key table')),
                ('keycol', models.CharField(help_text="the table's primary key column name", max_length=255, verbose_name='key table')),
                ('create_proc', models.CharField(blank=True, default=None, help_text='the SQL code when an LDAP create is called', max_length=255, null=True, verbose_name='on create')),
                ('delete_proc', models.CharField(blank=True, default=None, help_text='the SQL code when an LDAP delete is called', max_length=255, null=True, verbose_name='on delete')),
                ('expect_return', models.IntegerField(default=0, help_text='what to expect when the query is successful (ie not an error)', verbose_name='expect return')),
            ],
            options={
                'verbose_name_plural': 'ldap oc mappings',
                'verbose_name': 'ldap oc mapping',
                'db_table': 'ldap_oc_mappings',
            },
        ),
        migrations.AddField(
            model_name='ldapentry',
            name='oc_map',
            field=models.ForeignKey(help_text='refers back to the id of the relevant objectClass in the ldap_oc_mappings table', on_delete=django.db.models.deletion.CASCADE, to='slapd_sql.LdapOcMapping'),
        ),
        migrations.AddField(
            model_name='ldapentriesobjectclasses',
            name='entry',
            field=models.ForeignKey(help_text='refers back to the id of the relevant objectClass in the ldap_oc_mappings table', on_delete=django.db.models.deletion.CASCADE, to='slapd_sql.LdapEntry'),
        ),
        migrations.AddField(
            model_name='ldapattrmapping',
            name='oc_map',
            field=models.ForeignKey(help_text='refers back to the id of the relevant objectClass in the ldap_oc_mappings table', on_delete=django.db.models.deletion.CASCADE, to='slapd_sql.LdapOcMapping'),
        ),
        migrations.AlterUniqueTogether(
            name='ldapentry',
            unique_together=set([('oc_map', 'keyval')]),
        ),
    ]
